services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
# networks:
#   default:
#     name: rm101
#     external: true
