# entities for linux commands and status

mqtt:
# Ubuntu Server
  - button:
      name: "UbuntuSever_Reboot"
      command_topic: "ubuntu_server1/cmd"
      payload_press: "reboot"
  - button:
      name: "UbuntuSever_Update_containers"
      command_topic: "ubuntu_server1/cmd"
      payload_press: "update_containers"

  - sensor:
      name: "UbuntuServer_Status"
      state_topic: "ubuntu_server1/stat"



